### ISSUE TITLE
Compilation problems with -O3 (missing symbols like _ZGVdN4vv___pow_finite )

### ISSUE THREAD

**Issue by exaexa** [kasperdanielhansen/Rgraphviz#12]
Hello,

I just noticed that on newer `gcc`s, Rgraphviz fails to install with too much optimization (`-O3`). Same issue is described here:

https://support.bioconductor.org/p/128118/

Setting `-O2` instead of `-O3` fixes the problem for me. Removing `-march=native` from both R runtime and from compiled library does not help.

It would be great to check for this problem during Rgraphviz installation, or possibly override the settings in the config stage. Or, at very least, provide a decent/helpful error message -- googling that this is caused by optimization flags (which is, say, fishy by itself) took me quite some time.

Unfortunately, I was unable to find the source of actual error-- the missing symbol is some kind of SSE-enabled `powf`, but I did not find from where (and why) it is actually pulled.

Thanks a lot!
-mk

**Comment by mattdowle** [comment]
Thank you @exaexa for posting this solution!  I had the same problem and reducing from -O3 to -O2 also fixes it for me.

**Comment by fizwit** [comment]
This is still an issue with GCC 10.2, with Rgraphviz 2.38.0.  CFLAGS define -O2, but the error still happens.

Fixing a missing symbol by changing the optimization was a good clue.  The actual optimization is with the `_finite` math functions in GNU libc are versions of their simpler namesakes which support gcc's `-ffinite-math-only` optimization. For example, where `acosh()` has well defined behavior for infinities, the function `__acosh_finite()` is a (presumably faster) variant to which it is not legal to pass infinities.

the CFLAG -fnofinite-math-only will turn off this optimization behavior with GCC.

**Comment by exaexa** [comment]
@fizwit thanks for explaining the root cause! Could be much easier to make a check just for `finite-math-only`.

**Comment by exaexa** [comment]
(just thinking, should this be reported upstream or not?)

**Comment by fizwit** [comment]
some people are fixing the issue with: -fno-builtin and one other post mentioned that if -lm is not included on every compile/link command that the problem could occur. The headers for the __finite math operators are on the system I am using. I still have a more testing to do.

**Comment by kasperdanielhansen** [comment]
I believe this is fixed in 2.42.2

**Comment by exaexa** [comment]
great thanks!
