### ISSUE TITLE
Rgraphviz installation error on Ubuntu 21.10 (undefined symbol: _ZGVbN2vv_pow)

### ISSUE THREAD

**Issue by hpages** [kasperdanielhansen/Rgraphviz#14]
Hi Kasper,

I'm getting the following load-time error on my Ubuntu 21.10 laptop when I try to install **Rgraphviz**:

    Error: package or namespace load failed for ‘Rgraphviz’:
     .onLoad failed in loadNamespace() for 'Rgraphviz', details:
      call: value[[3L]](cond)
      error: unable to load shared object '/home/hpages/R/R-4.2.r81105/library/Rgraphviz/libs/Rgraphviz.so':
      /home/hpages/R/R-4.2.r81105/library/Rgraphviz/libs/Rgraphviz.so: undefined symbol: _ZGVbN2vv_pow

I'm seeing this error in release (BioC 3.14 + R 4.1) with **Rgraphviz** 2.38.0, as well as in devel (BioC 3.15 + R 4.2) with **Rgraphviz** 2.39.0 (pre Tomas' patch) and **Rgraphviz** 2.39.1 (post Tomas' patch).

The command that `R CMD INSTALL` is using on my machine for the linking step is:

    /usr/bin/gcc -shared -L/home/hpages/R/R-4.2.r81105/lib -L/usr/local/lib -o Rgraphviz.so LL_funcs.o Rgraphviz.o RgraphvizInit.o agopen.o agread.o agwrite.o bezier.o buildEdgeList.o buildNodeList.o doLayout.o graphvizVersion.o init.o libxdot.a libgvplugin_dot_layout.a libgvplugin_neato_layout.a libgvplugin_core.a libgvc.a libpathplan.a libgraph.a libcdt.a -lz -L/home/hpages/R/R-4.2.r81105/lib -lR

Note that the same command is used on [nebbiolo2](https://bioconductor.org/checkResults/3.14/bioc-LATEST/Rgraphviz/nebbiolo2-install.html) and [nebbiolo1](https://bioconductor.org/checkResults/3.15/bioc-LATEST/Rgraphviz/nebbiolo1-install.html) (except of course for the `/home/hpages/R/R-4.2.r81105/lib` path). As you can see it doesn't have `-lm`. However, since the C code in **Rgraphviz** calls `pow()`, which belongs to the C math library (`<math.h>`), it seems that the linking command should have `-lm`, at least in theory.

Adding `-lm` solves the problem on my laptop.

I'm not sure why we see this problem on Ubuntu 21.10 and not on Ubuntu 20.04 (the latter being what we have on the Bioconductor daily builders). Maybe something has changed in the standard C and math libraries between the two Ubuntu versions, I don't know.

Thanks,
H.

**Comment by kasperdanielhansen** [comment]
We have had a very similar error reported from people trying to compile with `-O3` under GCC and it was fixed by using `-O2` instead. It sounds like it can also be fixed by adding `-lm` which sounds like a better solution. I will try to get this done by release and perhaps also upgrade Graphviz which may already have this fix applied - the version we use is old by now.

**Comment by hpages** [comment]
@kasperdanielhansen Still can't install **Rgraphviz**. Other people using Ubuntu >= 21.10 might be affected (Ubuntu 22.04 LTS got released last week). Do you want me to submit a PR?

**Comment by hpages** [comment]
@kasperdanielhansen Hi Kasper, any chance this can be fixed? Would be nice :wink: It's a very simple one-line change in `Makevars.in`, `Makevars.win`, and `Makevars.ucrt`. Every time I install or re-install **Rgraphviz** on my Ubuntu 22.04 LTS system I get this error and need to manually apply the above fix to `Makevars.in`. Let me know how I can help. Thanks!

**Comment by kasperdanielhansen** [comment]
I believe this is fixed in 2.42.2.

**Comment by hpages** [comment]
I just tried it on my Ubuntu 22.04 laptop and it worked. Thx!
