### ISSUE TITLE
&& or || in upcoming R release

### ISSUE THREAD

**Issue by audreyqyfu** [kasperdanielhansen/Rgraphviz#15]
Dr. Hansen,

We have a CRAN R package that imports the plot function from Rgraphviz.  It looks like that CRAN will release a new version of R that makes the following change:
"Calling && or || with either argument of length greater than one is now an error. [Scheduled for May 2.]"
In fact, CRAN is already issuing warnings to us developers about this change during routine checks of CRAN packages.  Just wondering whether Rgraphviz has plans for a new release to address this issue.  

Thanks for your attention and assistance.

Best regards,
Audrey

**Comment by kasperdanielhansen** [comment]
I checked the source in 2.42.2 and I believe it is for sure fixed in this version, but it was probably fixed earlier.
