### ISSUE TITLE
Installing Rgraphviz on raspberry pi 64-bit

### ISSUE THREAD

**Issue by arnaudcol** [kasperdanielhansen/Rgraphviz#18]
I am running into issues installing Rgraphviz on my raspberry pi.  I am running the 64-bit OS with all libraries and dependencies recently updated.  Install log is as follows:

* installing *source* package ‘Rgraphviz’ ...
** using staged installation
configure: Using bundled Graphviz.
configure: Searching for the compilers specified by R.
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++11 accepts -g... yes
configure: Preparing to compile Graphviz.
configure: Configuring bundled Graphviz.
checking build system type... config/config.guess: unable to guess system type

This script, last modified 2009-11-20, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (config/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2009-11-20

uname -m = aarch64
uname -r = 5.15.32-v8+
uname -s = Linux
uname -v = #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022

/usr/bin/uname -p = unknown
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              = aarch64
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = aarch64
UNAME_RELEASE = 5.15.32-v8+
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022
configure: error: cannot guess build type; you must specify one
make: *** No rule to make target 'install'.  Stop.
cp: cannot stat '/tmp/RtmpQ0GbAP/R.INSTALL268624ed1b5f/Rgraphviz/src/libunix/lib/*': No such file or directory
cp: cannot stat '/tmp/RtmpQ0GbAP/R.INSTALL268624ed1b5f/Rgraphviz/src/libunix/lib/graphviz/*': No such file or directory
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for deflateBound in -lz... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for whether compiler has bool... yes
configure: Using the following compilation and linking flags for Rgraphviz
configure:    PKG_CFLAGS= -I/tmp/RtmpQ0GbAP/R.INSTALL268624ed1b5f/Rgraphviz/src/libunix/include/graphviz
configure:    PKG_LIBS=libxdot.a libgvplugin_dot_layout.a libgvplugin_neato_layout.a libgvplugin_core.a libgvc.a libpathplan.a libgraph.a libcdt.a -lz
configure:    GVIZ_DEFS=-DGRAPHVIZ_MAJOR=2 -DGRAPHVIZ_MINOR=28 -DGRAPHVIZ_STATIC -DHAVE_STDBOOL_H=1 -DHAVE_BOOL=1
configure: Compiling using Graphviz version: '2.28.0'.
configure: Using bundled Graphviz: 'TRUE'.
configure: creating ./config.status
config.status: creating R/graphviz_build_version.R
config.status: creating src/Makevars
** libs
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG     -I/tmp/RtmpQ0GbAP/R.INSTALL268624ed1b5f/Rgraphviz/src/libunix/include/graphviz -DGRAPHVIZ_MAJOR=2 -DGRAPHVIZ_MINOR=28 -DGRAPHVIZ_STATIC -DHAVE_STDBOOL_H=1 -DHAVE_BOOL=1 -fpic  -g -O2 -ffile-prefix-map=/build/r-base-87i4cL/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c LL_funcs.c -o LL_funcs.o
In file included from LL_funcs.c:1:
common.h:16:10: fatal error: gvc.h: No such file or directory
   16 | #include <gvc.h>
      |          ^~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:172: LL_funcs.o] Error 1
ERROR: compilation failed for package ‘Rgraphviz’
* removing ‘/root/R/aarch64-unknown-linux-gnu-library/4.0/Rgraphviz’

The downloaded source packages are in
        ‘/tmp/RtmpxKlRZO/downloaded_packages’
Warning message:
In install.packages(...) :
  installation of package ‘Rgraphviz’ had non-zero exit status

Any suggestions?

**Comment by benz0li** [comment]
See PR https://github.com/kasperdanielhansen/Rgraphviz/pull/16.

**Comment by kasperdanielhansen** [comment]
I believe this is fixed in 2.42.2.

**Comment by benz0li** [comment]
Confirmed. [Rgraphviz v2.41.2](https://www.bioconductor.org/packages/devel/bioc/html/Rgraphviz.html) builds on Linux aarch64.
